export enum ActivityActionEnum {
  PROJECT_CREATED = 'PROJECT_CREATED',
  PROJECT_UPDATED = 'PROJECT_UPDATED',
  PROJECT_DELETED = 'PROJECT_DELETED',
  TASK_CREATED = 'TASK_CREATED',
  TASK_STATUS_UPDATED = 'TASK_STATUS_UPDATED',
  TASK_ASSIGNED = 'TASK_ASSIGNED',
  TASK_UPDATED = 'TASK_UPDATED',
  TASK_FLAGGED_OVERDUE = 'TASK_FLAGGED_OVERDUE',
  COMMENT_ADDED = 'COMMENT_ADDED',
  CLIENT_CREATED = 'CLIENT_CREATED',
}

export enum NotificationTypeEnum {
  TASK_ASSIGNED = 'TASK_ASSIGNED',
  TASK_IN_REVIEW = 'TASK_IN_REVIEW',
  TASK_OVERDUE = 'TASK_OVERDUE',
  TASK_COMPLETED = 'TASK_COMPLETED',
  SYSTEM_ALERT = 'SYSTEM_ALERT',
}
